language: c
sudo: false

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_miniconda.sh

script:
  - echo travis_fold:start:conda.build.package
  - conda build devtools/conda-recipe
  - echo travis_fold:end:conda.build.package

env:
  - CONDA_PY=2.7
  - CONDA_PY=3.5
  - CONDA_PY=3.6
  - CONDA_PY=3.7